# Projekt: IPK - 01: Webovy klient
# Autor:   Klara Necasova
# Datum:   brezen 2016
 
CC=g++                     # překladač jazyka C++
FLAGS= -Wall -pedantic -g  # parametry překladace

webclient: webclient.cpp
	$(CC) $(FLAGS) webclient.cpp -o webclient

